enable:
  issues: false
  prs: true

labels:
  # Build files
  'build':
    include:
      - '\bbuild:\b'
  # Chores
  'chore':
    include:
      - '\bchore:\b'
  # Continuos Integration
  'ci':
    include:
      - '\bci:\b'
  # Modify docs
  'docs':
    include:
      - '\bdocs:\b'
  # Add feature
  'feat':
    include:
      - '\bfeat:\b'
  # Fix bug
  'fix':
    include:
      - '\bfix:\b'
  # Refactor code
  'refactor':
    include:
      - '\brefactor:\b'
  # Revert commit
  'revert':
    include:
      - '\brevert:\b'
  # Style code (code formatting)
  'style':
    include:
      - '\bstyle:\b'
  # Modifying style code
  'design':
    include:
      - '\bdesign:\b'
  # Add test code
  'test':
    include:
      - '\btest:\b'
