enable:
  issues: false
  prs: true

labels:
  # Build files
  'build':
    include:
      - '\bbuild\b'
  # Chores
  'chore':
    include:
      - '^chore\b'
  # Continuos Integration
  'ci':
    include:
      - '^ci\b'
  # Modify docs
  'docs':
    include:
      - '^docs\b'
  # Add feature
  'feat':
    include:
      - '^feat\b'
  # Fix bug
  'fix':
    include:
      - '^fix\b'
  # Refactor code
  'refactor':
    include:
      - '^refactor\b'
  # Revert commit
  'revert':
    include:
      - '^revert\b'
  # Style code (code formatting)
  'style':
    include:
      - '^style\b'
  # Modifying style code
  'design':
    include:
      - '^design\b'
  # Add test code
  'test':
    include:
      - '^test\b'
